names = ['Margaret', 'Karen', 'Rebecca', 'Steven', 'David', 'Susan', 'Catherine', 'Carol', 'Charles', 'Ruth', 'Brian', 'Kevin', 'Timothy', 'Joseph', 'Amanda', 'Kathleen', 'Peter', 'Robert', 'Pamela', 'Barbara', 'James', 'Daniel', 'Jennifer', 'Eric', 'Henry', 'Kenneth', 'Andrew', 'Roger', 'Anthony', 'Diane', 'Sharon', 'Ann', 'Martha', 'Donna', 'Joyce', 'Sandra', 'Edward', 'Walter', 'Christine', 'Richard', 'Larry', 'John', 'Cynthia', 'Amy', 'Dorothy', 'Gregory', 'George', 'Shirley', 'Frances', 'Stephanie', 'Brenda', 'Carolyn', 'Jeffrey', 'Matthew', 'Helen', 'Stephen', 'William', 'Nancy', 'Angela', 'Michelle', 'Linda', 'Thomas', 'Joshua', 'Raymond', 'Deborah', 'Debra', 'Christopher', 'Lisa', 'Melissa', 'Maria', 'Scott', 'Elizabeth', 'Laura', 'Ronald', 'Paul', 'Virginia', 'Dennis', 'Marie', 'Carl', 'Betty', 'Douglas', 'Anna', 'Patricia', 'Donald', 'Ryan', 'Kimberly', 'Janet', 'Jessica', 'Arthur', 'Patrick', 'Frank', 'Mary', 'Harold', 'Jason', 'Gary', 'Michael', 'Jerry', 'Mark', 'Sarah', 'Jose']
sentences = [
	"The curves of our lips rewrite history",
	"A dream all a dream that ends in nothing and leaves the sleeper where he lay down but I wish him to know that he inspired it",
	"Whatever our souls are made of his and mine are the same",
	"If equal affection cannot be let the more loving one be me",
	"And now that we don't have to be perfect we can be good",
	"There are more things in Heaven and Earth Horatio than are dreamt of in their philosophy",
	"It might be that to surrender to happiness was to accept defeat but it was a defeat better than many victories",
	"In spite of everything I still believe people are really good at heart",
	"How wild it was to let it be",
	"She was lost in her longing to understand",
	"The half life of love is forever",
	"I celebrate myself and sing myself",
	"Tomorrow is always fresh with no mistakes in it",
	"I would always rather be happy than dignified",
	"It frightened him to think what must have gone to the making of her eyes",
	"For poems are like rainbows; they escape you quickly",
	"So we beat on boats against the current borne back ceaselessly into the past",
	"It does not do well to dwell on dreams and forget to live remember that",
	"My thoughts are stars I cannot fathom into constellations",
	"Some infinities are bigger than other infinities",
]
strings = [
	"flagsaretasty",
	"foodforthought",
	"wholikesprogrammingforfun",
	"whoneedssleep",
	"cookiesaretastierthanflags",
	"opendoorsareopportunities",
	"whyissolvingproblemssofun",
	"whatstheanswertolife",
	"learningshouldbefun",
	"trialanderroristhekey",
]
syllables = [
	"sa",
	"so",
	"la",
	"lo",
	"pa",
	"po",
	"to",
	"ta",
	"do",
	"da",
	"go",
	"ga",
	"bo",
	"bi"
]